spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_aggregator
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format.sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

solidbank.api.url: https://shop.stage.klix.app/api/SolidBank/applications
fastbank.api.url: https://shop.stage.klix.app/api/FastBank/applications
